#!/bin/bash

version=${1%%-*}
v=${version//./ };
array=( $v )

sed -e "s/@PURPLE_MAJOR_VERSION@/${array[0]}/g" \
        -e "s/@PURPLE_MINOR_VERSION@/${array[1]}/g" \
        -e "s/@PURPLE_MICRO_VERSION@/${array[2]}/g" version.h.in > version.h
